name: 🐠 Feature Request
description: Suggest an idea for this project
title: "🐠 "
type: feature
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for this feature.
    options:
    - label: I have searched the existing open and closed issues
      required: true
    - label: I have searched the existing discussions
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: Is your feature request related to a problem? Please describe.
  validations:
    required: false
- type: textarea
  attributes:
    label: Proposed Behavior
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternative Solutions
    description: Describe alternatives you've considered.
    placeholder: |
      A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: dropdown
  id: plugin_version
  attributes:
    label: Plugin Version
    description: What version of the plugin are you running?
    options:
      - "5.0"
      - "5.1"
      - "5.2"
      - "5.3"
      - "6.0"
      - Other
    default: 4
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
