#
# © 2024-present https://github.com/cengiz-pz
#

platform_version=16.0
swift_version=5.9
frameworks=Foundation.framework,AppTrackingTransparency.framework
embedded_frameworks=res://ios/framework/GoogleMobileAds.xcframework,res://ios/framework/UserMessagingPlatform.xcframework
flags=-ObjC,-Wl,-weak-lswiftCore,-weak-lswiftObjectiveC,-weak-lswift_Concurrency
