#
# © 2026-present https://github.com/cengiz-pz
#

name: Android Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'common/config/**'
      - 'common/**/*.gradle.kts'
      - 'android/config/**'
      - 'android/src/**'
      - 'android/**/*.gradle.kts'

jobs:
  build-android-debug:
    runs-on: ubuntu-22.04

    steps:
      # ── Checkout ────────────────────────────────────────────────────────────
      - uses: actions/checkout@v6

      # ── Node ────────────────────────────────────────────────────────────────
      - name: Install Node
        uses: ./.github/actions/install-node

      # ── Java ────────────────────────────────────────────────────────────────
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # ── Gradle ──────────────────────────────────────────────────────────────
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x common/gradlew

      # ── Prepare for Android build ───────────────────────────────────────────
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # ── Run Android build ───────────────────────────────────────────────────
      - name: Build Android debug
        working-directory: common
        run: ./gradlew buildAndroidDebug --no-daemon --stacktrace
